src/cayaldjango/cayaldjango/urls.py
from django.contrib import admin
from django.urls import path
from cayaldjango  import views



from cuentas.views import login_view, register_view, logout_view, logout_def


urlpatterns = [
    
    #path('accounts/login/', login_view),
    
    path('', login_view, name='home'),
    path('accounts/logout/', logout_def, name='salir'),
    path('accounts/register/', register_view),
    path('accounts/logout/', logout_view),
    path('index/', views.login_view, name='index'),
    path('index/productos/', views.product_view, name="product"),
    path('index/ordenes/', views.orden_view, name="ordenes"),
    path('agregar/', views.CreateProduct.as_view(), name="add_product"),
    path('modificar/<int:pk>/', views.EditProducto.as_view(), name="edit_product"),
    path('eliminar/<int:pk>/', views.DeleteProduct.as_view(), name="delete_product"),
    path('admin/', admin.site.urls),
    
    
] 

src/cayaldjango/productos/models.py
from django.db import models

''' definimos todos los objetos llamados Models '''
class Producto(models.Model):
    Producto     =  models.CharField(max_length=20,)
    Distribuidor =  models.TextField(max_length=100)
    Descripcion  =  models.DateField(auto_now_add=False, auto_now=False)
    Precio       =  models.DecimalField(max_digits=11, decimal_places=2)
    Peso         =  models.DecimalField(max_digits=5, decimal_places=2)
    Imagen       =  models.ImageField(upload_to='user_directory_path')

    def __str__(self):
        return self.Producto

src/cayaldjango/productos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from .models import Producto
from .form import FormProduct
from files.forms import UploadForm

'''Una View es un lugar donde ponemos la "lógica" de nuestra aplicación'''

''' 
Pedirá información del Modelo
'''
#Create your views here 
def product_list_view(request):
    producto = Producto.object.all()
    form =  FormProduct(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save(commit = True)
            return redirect('product_list_view')
    #Manejo de paginacion
    page = request.GET.get('page',1)
    paginator = Paginator(productos,3)
    try:
        producto_page = paginator.page(page)
    except PageNotAnInteger:
        producto_page = paginator.page(1)
    except EmptyPage:
        producto_page = paginator.page(paginator.num_pages)
    
    return render(request, 'templates/producto.html', {'productos': producto_page, 'form': form})

def delete_producto(request, id):
    producto = get_object_or_404(Item, id=id)
    #producto = Producto.objects.filter(id=id)
    if  producto:
        producto.delete()
    return redirect ('product_list_view')

def edit_producto (request, id):
    producto = get_object_or_404(Item, id=id)
    form = ProductoCreationForm(request.POST or None, instance = producto)
    if request.method =='POST':
        if form.is_valid():
            form.save()
            return redirect(product_list_view)
    return render(request, 'templates/modificar.html', {'producto' : producto, 'form' : form} )




def post_new(request):
    form = PostForm()
    return render(request, 'productos/agregar.html', {'form': form}) 

def upload_file(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
        	newdoc = Document(filename = request.POST['filename'],Imagen = request.FILES['docfile'])
        	newdoc.save(form)
        	return redirect("uploads")
    else:
        form = UploadForm()
    #tambien se puede utilizar render_to_response
    #return render_to_response('upload.html', {'form': form}, context_instance = RequestContext(request))
    return render(request, 'upload.html', {'form': form})

src/cayaldjango/templates/agregar.html
{% load static %}
<!doctype html>
<html lang="esp">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Sinik software Development</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <img src="/static/logo.png"  style="width:100px" clear="left" bg="dark">
      <input class="form-control form-control-dark w-100" type="text" placeholder="Buscar" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="{% url 'product' %}">Salir</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link " href="{% url 'index' %}">
                  <span data-feather="home"></span>
                  Inicio<span class="sr-only" >(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link  " href="{% url 'ordenes' %}" >
                  <span data-feather="file"></span>
                  Ordenes
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'product' %}" >
                  <span data-feather="shopping-cart"></span>
                  Productos
                </a>
              </li>
              
              
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  Reportes
                </a>
            </ul>
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    
                  </ul>
                </div>
              </nav>
              
              <div style="padding:4.2% 30% 20% 20%">
              
                <form method="POST" class="post-form" enctype="multipart/form-data" data-parsley-validate>
                {% csrf_token %}<!--Capa de proteccion contra la falsificacion de peticiones-->
                
                <p><label for="id_Producto">Nombre del Producto:</label> <input type="text"  name="Producto" class="form-control" minlength="5" maxlength="40" required pattern="[A-Za-z]+" required id="id_Producto" data-parsley-required data-parsley-required-message="Este campo es requerido" data-parsley-error-message='Este caracter es invalido.' > <span class="helptext">Ingrese el nombre del producto</span></p>
              <p><label for="id_Distribuidor">Distribuidor:</label> <select name="Distribuidor" class="form-control" maxlength="100" id="id_Distribuidor">
              <option value="Pollos Hermanos">Pollos Hermanos</option>

              <option value="Vegetales Don Marco">Vegetales Don Marco</option>



              </select> <span class="helptext">Por favor escoja una opción</span></p>
              <p><label for="id_Precio">Valor monetario:</label>
               <input type="number" name="Precio" min="1" max="20000" step="1" class="form-control" step="0.01" required id="id_Precio" data-parsley-required data-parsley-required-message="Este campo es requerido" data-parsley-error-message='El  valor debe ser entre 1 y 20000 .' > <span class="helptext">Solo se permiten 5 digitos enteros</span></p>
              <p><label for="id_Peso">kilaje:</label>
                 <input type="number" name="Peso" min=0 step="0.1" max="1000" class="form-control" step="0.01" required id="id_Peso" data-parsley-required data-parsley-required-message="Este campo es requerido" data-parsley-error-message='El  valor debe ser entre 0 y 1000 .'></p>
              <tr><th><label for="id_Imagen">Imagen del Producto:</label></th><td>
                <input type="file" name="Imagen" accept="image/*" required id="id_Imagen"><br><span class="helptext">Seleccione la imagen correcta</span></td></tr>
              <p><label for="id_Descripcion">Fecha de entrada producto:</label> 
                <input type="date"value="2019-01-01"  name="Descripcion" class="form-control rounded-input rounded-input-med txt12" required id="id_Descripcion" data-parsley-required data-parsley-required-message="Este campo es requerido"> </p>
                <button type="submit"  class="btn btn-sm btn-primary btn-flat" >Guardar</button>
                </form>
              </div>

          

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    
  </body>
</html>

src/cayaldjango/templates/eliminar.html
{% load static %}
<!doctype html>
<html lang="esp">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Sinik software Development</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/dashboard.css" rel="stylesheet">
  </head>

  <body>
     
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Sinik</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Buscar" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="{% url 'product' %}">Salir</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link " href="#">
                  <span data-feather="home"></span>
                  Inicio <span class="sr-only"></span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file"></span>
                  Ordenes
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="shopping-cart"></span>
                  Productos
                </a>
             
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  Reportes
                </a>
            </ul>
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    
              </nav>
              -->
              <nav style="padding:15% 30% 20% 20%" >
              <form method="post">{% csrf_token %}
                  <h2>Esta seguro de que desea borrar este producto <strong>"{{ object }}"</strong>?</h2>
                  <a href="{% url 'product' %}">Cancelar</a>
                  <button type="submit" class="btn btn-danger">Borrar</button>
              </form>
              </nav>

          

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    
  </body>
</html>

src/cayaldjango/templates/login.html
{% load static %}

<!doctype html>
<html lang="esp">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Sinik software Development</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/sign.css" rel="stylesheet">
  </head>

  <body class="text-center">
  
    <form role="form" data-toggle="validator" method="POST" class="form-signin">
    
      <img class="mb-4" src="/static/logocayal.png" alt="" width="72" height="72">
     <h1></h1>
     
    <form method="POST">
      
        <input type="hidden" name="csrfmiddlewaretoken" value="oayuAMQlBSe3nC5oV9DnhwBli0XH0CuvSNhIPocvTvMmfZX3yvItzkwc9cIjBgU5">
        {% csrf_token %}
         {{ form }}
        <button  class="btn btn-lg btn-primary btn-block"  type="submit">Iniciar Sesión </button>
        <p class="mt-5 mb-3 text-muted">&copy; 2016-2020</p>
    </form>
          
    </body>
</html>

src/cayaldjango/templates/modificar.html
{% load static %}
<!doctype html>
<html lang="esp">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Sinik software Development</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <img src="/static/logo.png"  style="width:100px" clear="left" bg="dark">
      <input class="form-control form-control-dark w-100" type="text" placeholder="Buscar" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="{% url 'product' %}">Salir</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link " href="{% url 'index' %}">
                  <span data-feather="home"></span>
                  Inicio<span class="sr-only" >(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link  " href="{% url 'ordenes' %}" >
                  <span data-feather="file"></span>
                  Ordenes
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'product' %}" >
                  <span data-feather="shopping-cart"></span>
                  Productos
                </a>
              </li>
              
              
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  Reportes
                </a>
            </ul>
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    
                  </ul>
                </div>
              </nav>
              
              <div  style="padding:4.2% 30% 20% 20%">
              
                <form method="POST" class="post-form" enctype="multipart/form-data" data-parsley-validate>
                {% csrf_token %}<!--Capa de proteccion contra la falsificacion de peticiones-->
                
                <p><label for="id_Producto">Nombre del Producto:</label>
                  <input type="text" name="Producto" class="form-control" value="{{form.Producto.value}}" minlength="5" maxlength="40" required pattern="[A-Za-z]+" required id="id_Producto" data-parsley-required data-parsley-required-message="Este campo es requerido" data-parsley-error-message='Este caracter es invalido.' > <span class="helptext">Ingrese el nombre del producto</span></p>
              <p><label for="id_Distribuidor">Distribuidor:</label>
               <select name="Distribuidor" value="{{form.Distribuidor.value}}"class="form-control" maxlength="100" id="id_Distribuidor">
              <option value="Pollos Hermanos">Pollos Hermanos</option>

              <option value="Vegetales Don Marco">Vegetales Don Marco</option>



              </select> <span class="helptext">Por favor escoja una opción</span></p>
              <p><label for="id_Precio">Valor monetario:</label>
               <input type="number"  name="Precio" min="1" max="20000" step="1" class="form-control" value="{{form.Precio.value}}" step="0.01" required id="id_Precio" data-parsley-required data-parsley-required-message="Este campo es requerido" data-parsley-error-message='El  valor debe ser entre 1 y 20000 .' > <span class="helptext">Solo se permiten 5 digitos enteros</span>
              </p>
              <p><label for="id_Peso">Kg:</label>
               <input type="txt" name="Peso" value="{{form.Peso.value}}" min=0 step="0.1" max="1000" class="form-control" step="0.01" required id="id_Peso" data-parsley-required data-parsley-required-message="Este campo es requerido" data-parsley-error-message='El  valor debe ser entre 0 y 1000 .'></p>
               
                
              <p>
              <label for="id_Descripcion">Fecha de entrada producto:</label>
                 <input type="date" value="{{form.Descripcion.value}}"  name="Descripcion" class="form-control rounded-input rounded-input-med txt12" required id="id_Descripcion" data-parsley-required data-parsley-required-message="Este campo es requerido">
                  </p>
                <button type="submit"  class="btn btn-sm btn-primary btn-flat" >Guardar</button>
                </form>
              </div>

    
          

    <!-- Bootstrap core JavaScript
    
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    
  </body>
</html>

src/cayaldjango/templates/ordenes.html
{% load static %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<!doctype html>
<html lang="esp">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Sinik software Development</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <img src="/static/logo.png"  style="width:100px" clear="left" bg="dark">
      <input class="form-control form-control-dark w-100" type="text" placeholder="Buscar" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="/accounts/logout/">Cerrar Sesión</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link " href="{% url 'index' %}">
                  <span data-feather="home"></span>
                  Inicio <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active " href="{% url 'ordenes' %}" >
                  <span data-feather="file"></span>
                  Ordenes
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="{% url 'product' %}">
                  <span data-feather="shopping-cart">(current)</span>
                  Productos
                </a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  Reportes
                </a>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Reportes guardados</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Por fecha
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Merma
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Ventas
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2"></h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Exportar</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                
              </button>
            </div>
          </div>

    <div class="table-responsive">
                                <table  class="table no-margin">
                                    <thead>
                                    <tr>
                                        <th>Código</th>
                                        <th>Número</th>
                                        <th>Cliente</th>
                                        <th>Fecha</th>
                                        <th>Subtotal</th>
                                        <th>Iva</th>
                                        <th>Total</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    
                                        <tr>
                                            <td>24</td>
                                            <td>000024</td>
                                            <td>Oscar German Torres Gaibor</td>
                                            <td>2019-03-18</td>
                                            <td>$27,00</td>
                                            <td>$3,24</td>
                                            <td>$30,24</td>
                                        </tr>
                                    
                                        <tr>
                                            <td>23</td>
                                            <td>000023</td>
                                            <td>Jessica Jessenia Guerra Gaibor</td>
                                            <td>2019-03-18</td>
                                            <td>$273,00</td>
                                            <td>$32,76</td>
                                            <td>$305,76</td>
                                        </tr>
                                    
                                        <tr>
                                            <td>22</td>
                                            <td>000022</td>
                                            <td>Jorge Luis Merchan Freire</td>
                                            <td>2018-11-24</td>
                                            <td>$161,00</td>
                                            <td>$19,32</td>
                                            <td>$180,32</td>
                                        </tr>
                                    
                                        <tr>
                                            <td>21</td>
                                            <td>000021</td>
                                            <td>Jessica Jessenia Guerra Gaibor</td>
                                            <td>2018-11-24</td>
                                            <td>$2005,00</td>
                                            <td>$240,60</td>
                                            <td>$2245,60</td>
                                        </tr>
                                    
                                        <tr>
                                            <td>20</td>
                                            <td>000020</td>
                                            <td>Oscar German Torres Gaibor</td>
                                            <td>2018-11-24</td>
                                            <td>$68,00</td>
                                            <td>$8,16</td>
                                            <td>$76,16</td>
                                        </tr>
                                    
                                        <tr>
                                            <td>19</td>
                                            <td>000019</td>
                                            <td>Jorge Luis Merchan Freire</td>
                                            <td>2018-11-24</td>
                                            <td>$27,00</td>
                                            <td>$3,24</td>
                                            <td>$30,24</td>
                                        </tr>
                                    
                                        <tr>
                                            <td>18</td>
                                            <td>000018</td>
                                            <td>Jessica Jessenia Guerra Gaibor</td>
                                            <td>2018-11-24</td>
                                            <td>$45,00</td>
                                            <td>$5,40</td>
                                            <td>$50,40</td>
                                        </tr>
                                    
                                        <tr>
                                            <td>17</td>
                                            <td>000017</td>
                                            <td>Jessica Jessenia Guerra Gaibor</td>
                                            <td>2018-11-24</td>
                                            <td>$20,00</td>
                                            <td>$2,40</td>
                                            <td>$22,40</td>
                                        </tr>
                                    
                                        <tr>
                                            <td>16</td>
                                            <td>000016</td>
                                            <td>Jorge Luis Merchan Freire</td>
                                            <td>2018-11-24</td>
                                            <td>$11,00</td>
                                            <td>$1,32</td>
                                            <td>$12,32</td>
                                        </tr>
                                    
                                        <tr>
                                            <td>15</td>
                                            <td>000015</td>
                                            <td>Jessica Jessenia Guerra Gaibor</td>
                                            <td>2018-11-24</td>
                                            <td>$1725,00</td>
                                            <td>$207,00</td>
                                            <td>$1932,00</td>
                                        </tr>
                                    
                                    </tbody>
                                </table>
                            </div>

          

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    
  </body>
</html>